version: '3'
services:
  gradimio-rembg:
    build:
      #network: host
      dockerfile: "Dockerfile"
      context: .
    ports:
      - "7860:7860"
    volumes:
      - .:/gradimio-rembg
      - ./src/u2net.onnx:/root/.u2net/u2net.onnx
    working_dir: /gradimio-rembg
    command: ["python3", "main.py"]
